---
title: "assignment"
author: "Rebecca Waag"
date: "9 5 2023"
output: html_document
---

# Week9: Normalization and enrichment analysis

## Exercise9: Preliminary Project Description

Come up with a preliminary plan for your project.

### 1. What is the topic?

Neuronal activity-induced changes in chromatin accessibility in the mouse hippocampus. For this, I will analyze two different datasets using either stress or kainic acid (KA, to model seizures) to cause neuronal activation. The results of both datasets will be compared to find regions that show altered accessibility under both stress and KA conditions.

### 2. What data will you be using?

Two ATAC-Seq datasets will be used for the analysis. The first one is assessing chromatin accessibility 1h after different stress protocols in male and female mice in the ventral hippocampus (https://pubmed.ncbi.nlm.nih.gov/36032404/),
The second one is assessing chromatin accessibility after 1h of kainic acid treatment in hippocampal neurons (https://www.nature.com/articles/s41593-019-0476-2).

### 3. What are the analyses you wish to reproduce, or the questions you wish to answer?

Questions:
1) Marrocco paper: Which regions are stress-responsive? 
2) Corces paper: Which regions are KA-responsive?
3) Which regions from the stress responsive ones also show responsiveness to KA treatment?

I want to reproduce the statistics for both datasets to find stress or KA responsive genes in the publications. Furthermore, I want to find regions that are responsive to both stress and KA treatment. Finally, I want to look into the identified regions to analyze where they are localized and perform a gene set enrichment analysis on the potentially identified genes. 